### ISSUE TITLE
Grouping documents breaks pagination & more

### ISSUE THREAD

**Issue by XigeTime** [elastic/app-search-reference-ui-react#46]
The grouping features seems to break pagination, total results, and results per page when using the Reference UI or Search UI.

To reproduce, download the Reference UI/Search UI and apply a grouping rule to one of the fields:
`"group": {
    "field": "doc_group"
}`

The total results, and results per page sections represent the amount results had they not been grouped together, I think this is a little misleading as the amount of visible documents would be considerably less.

The pagination has the same issue. Due to the app thinking there are more results to be shown, it calculates more pages than you need, then some of the pages show blank as there actually aren't that many results.

**Comment by XigeTime** [comment]
Digging further, I have noticed that when using the grouping feature it won't return any more than 100 results, as opposed to the 1000 allowed when not using the grouping feature.

When making a search I am receiving "172" as the **totalResults** value, however I can only view 100 of them. If I set the results to 200 per page, the totalResults comes through as 172, but the amount of actual results being returned by the API is still 100.

Changing the size field on the group doesn't seem to affect this.

**Comment by yakhinvadim** [comment]
Hey @XigeTime, thanks for opening this issue.
It looks like the bug comes from the underlying Search UI library, so I'm going to close this issue and continue the discussion in Search UI repo.
Search UI issue: https://github.com/elastic/search-ui/issues/412
