### ISSUE TITLE
Support for on-premise app-search

### ISSUE THREAD

**Issue by sespinosa** [elastic/app-search-reference-ui-react#47]
This app assumes that i'm using the swiftype service as the backend (i have my on premise app-search instance running), how i can make it work?

**Comment by XigeTime** [comment]
Hi @sespinosa, I think you need to look at the [Search UI](https://github.com/elastic/search-ui). The React Reference UI is just the Search UI pre-configured for your hosted App Search setup.

See here for using an alternate connector using the Search UI: https://github.com/elastic/search-ui/blob/master/ADVANCED.md#connectors-and-handlers

**Comment by JasonStoltz** [comment]
Hey @sespinosa, my apologies, I just noticed that this was not documented. You can use the `endpointBase` configuration to use this with self managed.

```
"endpointBase": "http://127.0.0.1:3002"
```

**Comment by sespinosa** [comment]
niiice
