### ISSUE TITLE
Failed to fetch CORS issue on Managed Swiftype

### ISSUE THREAD

**Issue by XigeTime** [elastic/app-search-reference-ui-react#50]
Hi when loading the reference ui from within the Swiftype dashboard we're receiving a CORS error:

> Access to fetch at 'https://host-64fz8w.api.swiftype.com/api/as/v1/engines/rydale/search.json' from origin 'https://app.swiftype.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'.

This is happening on all 3 of our live eCommerce sites during our black friday sales. I've had multiple customers call in having the same issue. I have contacted support via email, & community forums with no reply, status page has no update.

Please can we get someone looking into this!

Thanks

**Comment by omegahm** [comment]
Hi @XigeTime. Thanks for creating this issue. We are currently working on a fix that should be deployed any minute now.

**Comment by XigeTime** [comment]
Issue is fixed now. Closing.

**Comment by anuragchoudhary01** [comment]
@XigeTime I am facing this CORS issue with APP Search. 
Do we have any config which we need to set to allow it?
