### ISSUE TITLE
problem in text alignment   

### ISSUE THREAD

**Issue by chetan-v** [elastic/app-search-reference-ui-react#58]
Text alignment is at left. It should be at center.

**Actual Behaviour**
![Screenshot from 2020-06-13 20-13-13](https://user-images.githubusercontent.com/63091769/84571739-e1a9b180-adb2-11ea-89d5-dd238066262f.png)

**Expected Behaviour**
![Screenshot from 2020-06-13 20-12-47](https://user-images.githubusercontent.com/63091769/84571743-e5d5cf00-adb2-11ea-8584-1afb3d132ee2.png)

**Would you like to work on the issue?**
Yes, I want to do that.

**Comment by JasonStoltz** [comment]
I'll pass along that information to our design team. In the meantime, I will close this issue as this repository is not for the elastic.co website.
