### ISSUE TITLE
not able to run on 'http://localhost:3000/' 

### ISSUE THREAD

**Issue by sourav-atd** [elastic/app-search-reference-ui-react#59]
getting error : An unexpected error occurred: Failed to fetch

engin.json details:

{
  "endpointBase": "http://127.0.0.1:3002",
  "engineName": "engine",
  "hostIdentifier": "host-xXXXX",
  "searchKey": "private-xxxxxxxxxxxxxx",
  "searchFields": ["title", "states"],
  "resultFields": ["id", "title", "states", "description", "visitors"],
  "querySuggestFields": ["title"],
  "titleField": "title",
  "urlField": "https://host-x2hop8.api.swiftype.com",
  "sortFields": ["title", "anotherField"],
  "facets": ["states", "title"]
}

could you please help to resolve this error ?

**Comment by JasonStoltz** [comment]
Hello, sorry for the late reply.

For `urlField` you need to provide a field name for a field to use for links within your results.

For this data set, you would use the `nps_link` field.

Change to:
```
"urlField": "nps_link"
```

That should resolve your issue.
