### ISSUE TITLE
Does this work with Vue?

### ISSUE THREAD

**Issue by 684efs3** [elastic/app-search-reference-ui-react#67]
The Reference UI is great. I like how you can get the config straight from Elastic Cloud's App search. 

I am using Nuxt (Vue). Is there a way to get this to work in Vue?

**Comment by JasonStoltz** [comment]
Nope, this project is purely react.

This project is built on https://github.com/elastic/search-ui, which can be worked on at a lower level that *is* pure js, and hence compatible with Vue. But it would take some coding on your end.
